package com.jiyun.com.day07_greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.administrator.yintaidemo.db.adressdb.AdressBean;
import com.example.administrator.yintaidemo.entity.ShopCartEntity;

import com.jiyun.com.day07_greendao.AdressBeanDao;
import com.jiyun.com.day07_greendao.ShopCartEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adressBeanDaoConfig;
    private final DaoConfig shopCartEntityDaoConfig;

    private final AdressBeanDao adressBeanDao;
    private final ShopCartEntityDao shopCartEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adressBeanDaoConfig = daoConfigMap.get(AdressBeanDao.class).clone();
        adressBeanDaoConfig.initIdentityScope(type);

        shopCartEntityDaoConfig = daoConfigMap.get(ShopCartEntityDao.class).clone();
        shopCartEntityDaoConfig.initIdentityScope(type);

        adressBeanDao = new AdressBeanDao(adressBeanDaoConfig, this);
        shopCartEntityDao = new ShopCartEntityDao(shopCartEntityDaoConfig, this);

        registerDao(AdressBean.class, adressBeanDao);
        registerDao(ShopCartEntity.class, shopCartEntityDao);
    }
    
    public void clear() {
        adressBeanDaoConfig.clearIdentityScope();
        shopCartEntityDaoConfig.clearIdentityScope();
    }

    public AdressBeanDao getAdressBeanDao() {
        return adressBeanDao;
    }

    public ShopCartEntityDao getShopCartEntityDao() {
        return shopCartEntityDao;
    }

}
